### ISSUE TITLE
kibana dependency failed

### ISSUE THREAD

**Issue by jeanmi151** [georchestra/docker#182]
on master branch with Docker version 23.0.2, 

I am getting the following error: 
'dependency failed to start: container docker-kibana-1 has no healthcheck configured'

by modifying docker-compose.yml like that it works:
```
kibana:
    image: kibana:7.9.0
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://kibana:5601/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - ./resources/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
 ```
